### ISSUE TITLE
Provider configuration inside modules

### ISSUE THREAD

**Issue by brunobritodev** [Z4ck404/terraform-aws-eks-s3-csi-driver#13]
I attempted to utilize your module and noticed that configuring the provider is required. I'm curious whether this requirement was an intentional design choice or if there's other specific reason

**Comment by Z4ck404** [comment]
Hey @brunobritodev, 

Thanks for using the module.  
The provider configuration is included in the module and that's why I require the aws_region and the aws_profile name variables and the module should be usable as is without an additional provider configs.

```
module "eks-ebs-csi-driver" {
  source  = "Z4ck404/eks-ebs-csi-driver/aws"

  aws_profile      = "profile"
  aws_region       = "us-east-1"
  eks_cluster_name = "eks_name"

  install_vpc_cni_addon = true
}
```
